Arcpoc 598 (#928)
* skip spec fetch if its less than a week old and it exists. Added force fetch script to force fetching of spec. Reorder api:all script so if it fails midway we keep the old spec instead of deleting it straight away. cichecks script now calls test:unit directly.

* Add stylelint fix command to lint:fix

* fix husky script

* Improve husky speed

* remove concurrently from prod dependencies

* test pre-push

* add yarn build to pre-push

* test: bad test

* Revert "test: bad test"

This reverts commit 1908dc237f635eec95ec77b1f7ce12e5cbe5158a.

* test

* Revert "test"

This reverts commit fc47bbc7097b62c4fc093e2f19a494c500f9af65.

* update pre-commit to print better logs

* add better log text for prepush

* updating api fetch text

* Arcpoc 1109 (#926)

* Delete unused files, add unit tests for SQ marked at 0% coverage

* Clean up helpers, improve coverage

* sq issue fix

* code coverage

* Linter + configure jest coverage to ignore paths and paths to collect from and add global coverage

* sq config changes

* ARCPOC-1351 select all applications changes (#927)

* select all applications changes

* Paginate using the last successful search filter, not the live form

* address review comments, refactor and sq ternary fix, explicitly set isSelectingAll

* Update dependency jest-preset-angular to v16.1.5 (#919)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix coverage running on test:unit

---------

Co-authored-by: DavidTMann <d.mann@cgi.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,5 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
-
-yarn lint-staged
+if ! yarn lint-staged; then
+  printf 'Pre-commit failed: linter checks did not pass.' >&2
+  exit 1
+fi
