update pre-commit to print better logs

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,5 @@
 #!/bin/sh
-yarn lint-staged
+if ! yarn lint-staged; then
+  printf 'Pre-commit failed: linter checks did not pass.' >&2
+  exit 1
+fi
